Brazilian translation has been updated
nmrih/nmrih-localization-files pull request #158
Opened 2023-06-04 13:38 UTC by marcielcps

`Added nms drugstore brazilian translation`
`Added missing line on nms laundry`
`Fixed a word in closecaption brazilian file`

2023-06-04 13:41 UTC, felis-catus requested changes

2023-06-04 13:41 UTC, felis-catus commented on nmrih/maps/nms_drugstore_brazilian.txt
Can you convert the file encoding to UTF-16 BE BOM?

2023-06-04 17:39 UTC, marcielcps commented on nmrih/maps/nms_drugstore_brazilian.txt
Sure, sorry I thought it was already encoded, check again

2023-06-05 00:03 UTC, felis-catus commented on nmrih/maps/nms_drugstore_brazilian.txt
Looks good now, thank you!

2023-06-05 00:04 UTC, felis-catus approved these changes

2023-06-05 00:04 UTC, merged